#!/bin/bash
# setup_keychain.sh — Store COS pipeline secrets in macOS Keychain.
#
# Why Keychain: LaunchAgent shells don't source ~/.zshrc, so environment
# variables aren't available to scheduled tasks. Keychain entries are accessible
# from any process via `security find-generic-password`.
#
# Usage:   ./setup_keychain.sh
# Reads:   prompts for each secret (input is silent for passwords/keys)
# Writes:  Keychain entries under service prefix $SERVICE_PREFIX

set -e

SERVICE_PREFIX="${SERVICE_PREFIX:-cos-pipeline}"
USER_ACCOUNT="$USER"

echo "═══════════════════════════════════════════════════════════════"
echo "  COS Pipeline — macOS Keychain Setup"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Service prefix: $SERVICE_PREFIX"
echo "  Account:        $USER_ACCOUNT"
echo ""
echo "  Set SERVICE_PREFIX env var to use a different prefix:"
echo "    SERVICE_PREFIX=my-firm ./setup_keychain.sh"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

prompt_and_store() {
  local key="$1"
  local label="$2"
  local silent="$3"   # 1 = hidden input (passwords, API keys)

  local existing
  existing=$(security find-generic-password -s "$SERVICE_PREFIX/$key" -a "$USER_ACCOUNT" -w 2>/dev/null || echo "")

  if [ -n "$existing" ]; then
    echo "  ✓  $key already set (skipping — delete first to update)"
    return
  fi

  echo "  → $label"
  if [ "$silent" = "1" ]; then
    read -rs -p "    Value: " value
    echo ""
  else
    read -r -p "    Value: " value
  fi

  if [ -z "$value" ]; then
    echo "    (skipped — empty)"
    return
  fi

  security add-generic-password \
    -s "$SERVICE_PREFIX/$key" \
    -a "$USER_ACCOUNT" \
    -w "$value" \
    -U  # update if exists

  echo "    ✓ Stored"
  echo ""
}

# ── Required secrets ──────────────────────────────────────────────
echo "── REQUIRED ─────────────────────────────────────────────────"
echo ""
prompt_and_store "ANTHROPIC_API_KEY"     "Anthropic API key (sk-ant-...)"     1
prompt_and_store "DASHBOARD_USERNAME"    "Dashboard HTTP Basic Auth username" 0
prompt_and_store "DASHBOARD_PASSWORD"    "Dashboard HTTP Basic Auth password" 1

# ── Optional secrets ──────────────────────────────────────────────
echo "── OPTIONAL (press Enter to skip) ───────────────────────────"
echo ""
prompt_and_store "ASSEMBLYAI_API_KEY"    "AssemblyAI key for podcast transcription"  1
prompt_and_store "SMTP_PASSWORD"         "SMTP app password for briefing emails"      1
prompt_and_store "TWILIO_AUTH_TOKEN"     "Twilio auth token for phone recording"      1

# ── Generate load-secrets.sh helper ───────────────────────────────
LOAD_SCRIPT="$HOME/.cos-pipeline-load-secrets.sh"
cat > "$LOAD_SCRIPT" <<EOF
#!/bin/bash
# Auto-generated by setup_keychain.sh on $(date)
# Source this in any shell that needs pipeline secrets:
#     source ~/.cos-pipeline-load-secrets.sh

_kc() { security find-generic-password -s "$SERVICE_PREFIX/\$1" -a "$USER_ACCOUNT" -w 2>/dev/null; }

export ANTHROPIC_API_KEY="\$(_kc ANTHROPIC_API_KEY)"
export DASHBOARD_USERNAME="\$(_kc DASHBOARD_USERNAME)"
export DASHBOARD_PASSWORD="\$(_kc DASHBOARD_PASSWORD)"

# Optional — only export if set
ASSEMBLYAI_KEY=\$(_kc ASSEMBLYAI_API_KEY) && [ -n "\$ASSEMBLYAI_KEY" ] && export ASSEMBLYAI_API_KEY="\$ASSEMBLYAI_KEY"
SMTP_PW=\$(_kc SMTP_PASSWORD) && [ -n "\$SMTP_PW" ] && export SMTP_PASSWORD="\$SMTP_PW"
TWILIO_TOK=\$(_kc TWILIO_AUTH_TOKEN) && [ -n "\$TWILIO_TOK" ] && export TWILIO_AUTH_TOKEN="\$TWILIO_TOK"

unset -f _kc
EOF
chmod +x "$LOAD_SCRIPT"

echo "═══════════════════════════════════════════════════════════════"
echo "  ✓  Setup complete"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Loader script written to:  $LOAD_SCRIPT"
echo ""
echo "  To use in shell:           source $LOAD_SCRIPT"
echo "  To use in LaunchAgent:     have your wrapper script source it"
echo ""
echo "  To inspect a stored value: security find-generic-password -s '$SERVICE_PREFIX/KEY_NAME' -a '$USER_ACCOUNT' -w"
echo "  To delete a stored value:  security delete-generic-password -s '$SERVICE_PREFIX/KEY_NAME' -a '$USER_ACCOUNT'"
echo ""
