#!/usr/bin/env python3
"""
skills_catalog.py — Auto-regenerate the personal-skills inventory.

Walks ~/.claude/commands/*.md, extracts each skill's YAML frontmatter
description, and writes a flat alphabetical inventory to
~/dashboards/docs/MY-SKILLS-INVENTORY.md.

This is the *raw inventory* — the curated MY-SKILLS.md (with categories,
"NEW" stars, when-to-use hints) is hand-authored. This tool flags skills
that exist in ~/.claude/commands/ but are not yet linked from MY-SKILLS.md
so the curated doc doesn't fall behind reality.

Usage:
    python3 skills_catalog.py            # dry-run; prints inventory + drift
    python3 skills_catalog.py --apply    # write MY-SKILLS-INVENTORY.md
    python3 skills_catalog.py --check    # exit 1 if drift is detected (for CI)
"""
from __future__ import annotations
import argparse, re, sys
from datetime import datetime, timezone
from pathlib import Path

COMMANDS_DIR = Path.home() / ".claude" / "commands"
INVENTORY_PATH = Path.home() / "dashboards" / "docs" / "MY-SKILLS-INVENTORY.md"
CURATED_PATH = Path.home() / "dashboards" / "docs" / "MY-SKILLS.md"


def parse_skill(path: Path) -> dict:
    """Pull name + description from a command .md file."""
    name = path.stem
    text = path.read_text(errors="ignore")
    desc = ""
    # YAML frontmatter
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if m:
        fm = m.group(1)
        d = re.search(r"^description:\s*(.+?)$", fm, re.MULTILINE)
        if d:
            desc = d.group(1).strip().strip('"').strip("'")
    # Fallback: first non-blank line after frontmatter that isn't a heading
    if not desc:
        body = text[m.end():] if m else text
        for line in body.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            desc = line[:200]
            break
    return {"name": name, "description": desc, "path": str(path)}


def collect_skills() -> list[dict]:
    if not COMMANDS_DIR.exists():
        return []
    out = [parse_skill(p) for p in sorted(COMMANDS_DIR.glob("*.md"))]
    return out


def render_inventory(skills: list[dict]) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        "# MY-SKILLS-INVENTORY",
        "",
        f"Auto-generated by `tools/skills_catalog.py` on {today}. Do not hand-edit.",
        f"Curated view with categories + context lives in [MY-SKILLS.md](MY-SKILLS.md).",
        "",
        f"**Source of truth:** [`~/.claude/commands/`](file://{COMMANDS_DIR}) — one `.md` per skill.",
        f"**Count:** {len(skills)} personal slash commands.",
        "",
        "| Skill | Description |",
        "|---|---|",
    ]
    for s in skills:
        desc = s["description"].replace("|", "\\|") or "_(no description in frontmatter)_"
        lines.append(f"| `/{s['name']}` | {desc} |")
    lines.append("")
    return "\n".join(lines)


def detect_drift(skills: list[dict]) -> list[str]:
    """Skills present in commands/ but not referenced in MY-SKILLS.md.

    Tolerant of backslash-escaped markdown (some pipelines emit
    `\\`/name\\`` form) — strip leading backslashes before matching.
    """
    if not CURATED_PATH.exists():
        return [s["name"] for s in skills]
    raw = CURATED_PATH.read_text(errors="ignore")
    # Normalize: drop \-escapes so backticks/asterisks are recognizable
    curated = raw.replace("\\`", "`").replace("\\*", "*").replace("\\#", "#")
    missing = []
    for s in skills:
        if not re.search(rf"`/?{re.escape(s['name'])}\b`", curated):
            missing.append(s["name"])
    return missing


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true",
                    help="Write MY-SKILLS-INVENTORY.md (default: dry-run print).")
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if drift exists (skills in commands/ not in curated doc).")
    args = ap.parse_args()

    skills = collect_skills()
    if not skills:
        print(f"No skills found at {COMMANDS_DIR}")
        return 0

    inventory_md = render_inventory(skills)
    drift = detect_drift(skills)

    if args.apply:
        INVENTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
        INVENTORY_PATH.write_text(inventory_md)
        print(f"✓ wrote {INVENTORY_PATH} ({len(skills)} skills)")
    else:
        print(inventory_md)

    if drift:
        print(f"\n⚠ DRIFT — {len(drift)} skill(s) in commands/ but not referenced in {CURATED_PATH.name}:")
        for n in drift:
            print(f"  - /{n}")
        if args.check:
            return 1
    else:
        print(f"\n✓ no drift — every skill in commands/ is referenced in {CURATED_PATH.name}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
